[env]
SOPS_AGE_KEY_FILE = "{{ env.HOME }}/.config/sops/homelab.age"
MISE_SOPS_AGE_KEY_FILE = "{{ env.HOME }}/.config/sops/homelab.age"
_.file = ".env.yaml"
SERVICE_ROOT = "{{ config_root }}"
TRAEFIK_HOST = 'laptop'


[tasks."decrypt:certs"]
run = [
  'sops decrypt --output traefik/acme/acme.json traefik/acme.enc.json && chmod 600 traefik/acme/acme.json'
]

[tasks."encrypt:certs"]
run = [
  'sops encrypt --output traefik/acme.enc.json traefik/acme/acme.json'
]

[tasks."decrypt:secrets"]
run = [
  'mkdir -p secrets && echo ${CF_DNS_API_KEY} > secrets/CF_DNS_API_KEY.secret',
]

[tasks."deploy:m4"]
env.TRAEFIK_HOST = 'm4'
run = [
  'docker compose up -d'
]

[tasks."deploy:m1"]
env.TRAEFIK_HOST = 'm1'
run = [
  'docker compose up -d'
]

[tasks."deploy:laptop"]
run = [
  'docker compose up -d'
]


[settings]
experimental=true

[tools]
age = "latest"
sops = "latest"
